CREATE DATABASE IF NOT EXISTS LIBRARY_MANAGEMENT;

USE LIBRARY_MANAGEMENT;




CREATE TABLE IF NOT EXISTS GENRE(
    MA_TL NVARCHAR(10) NOT NULL PRIMARY KEY,
    TEN_TL NVARCHAR(40) NOT NULL ,
    MO_TA NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS AUTHOR (
    MA_TG NVARCHAR(10) NOT NULL PRIMARY KEY ,
    TEN_TG NVARCHAR(40) NOT NULL,
    EMAIL NVARCHAR(40),
    GIOI_THIEU NVARCHAR(100),
    GIOI_TINH NVARCHAR(10)
);

CREATE TABLE IF NOT EXISTS PUBLISHER(
    MA_NXB NVARCHAR(10) NOT NULL PRIMARY KEY ,
    TEN_NXB NVARCHAR(40),
    EMAIL NVARCHAR(40),
    DIA_CHI NVARCHAR(100),
    PHONE NVARCHAR(20),
    DESCRIPTION NVARCHAR(100)
);



CREATE TABLE IF NOT EXISTS BOOK (
    MA_SERIES NVARCHAR(40) NOT NULL PRIMARY KEY ,
    MA_SACH NVARCHAR(10) NOT NULL UNIQUE ,
    TEN_SACH NVARCHAR(40) NOT NULL ,
    MO_TA NVARCHAR(100) NOT NULL ,
    VI_TRI NVARCHAR(40) NOT NULL ,
    GIA LONG NOT NULL ,
    NAM_XUAT_BAN YEAR NOT NULL ,
    NGON_NGU NVARCHAR(20) NOT NULL ,
    TONG_SO_TRANG INT NOT NULL,
    DA_MUON BOOL NOT NULL
);


CREATE TABLE IF NOT EXISTS BOOK_AUTHOR (
    MA_SERIES NVARCHAR(10) NOT NULL,
    MA_TG NVARCHAR(10) NOT NULL,
    CONSTRAINT PK_BOOK_AUTHOR_MS_MTG PRIMARY KEY (MA_SERIES, MA_TG),
    CONSTRAINT FK_BA_AUTHOR_MATG FOREIGN KEY (MA_TG) REFERENCES AUTHOR(MA_TG),
    CONSTRAINT FK_BAU_BOOK_MASACH FOREIGN KEY (MA_SERIES) REFERENCES BOOK(MA_SERIES)
);

CREATE TABLE IF NOT EXISTS BOOK_PUBLISHER (
    MA_SERIES NVARCHAR(10) NOT NULL,
    MA_NXB NVARCHAR(10) NOT NULL,
    CONSTRAINT PK_BOOK_AUTHOR_MS_MTG PRIMARY KEY (MA_SERIES, MA_NXB),
    CONSTRAINT FK_BP_BOOK_MASACH FOREIGN KEY (MA_SERIES) REFERENCES BOOK(MA_SERIES),
    CONSTRAINT FK_BP_PUBLISHER_MA_NXB FOREIGN KEY (MA_NXB) REFERENCES PUBLISHER(MA_NXB)
);

CREATE TABLE IF NOT EXISTS BOOK_GENRE (
    MA_SERIES NVARCHAR(10) NOT NULL,
    MA_TL NVARCHAR(10) NOT NULL,
    CONSTRAINT PK_BOOK_AUTHOR_MS_MTG PRIMARY KEY (MA_SERIES, MA_TL),
    CONSTRAINT FK_BG_BOOK_MASACH FOREIGN KEY (MA_SERIES) REFERENCES BOOK(MA_SERIES),
    CONSTRAINT FK_BG_GENRE_MATL FOREIGN KEY (MA_TL) REFERENCES GENRE(MA_TL)
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
    MA_KH NVARCHAR(20) NOT NULL PRIMARY KEY ,
    TEN NVARCHAR(40) NOT NULL,
    NGAY_SINH DATE,
    DIA_CHI NVARCHAR(100) NOT NULL ,
    CCCD NVARCHAR(20) NOT NULL ,
    EMAIL NVARCHAR(40) ,
    PHONE NVARCHAR(20),
    GIOI_TINH NVARCHAR(10)
);

CREATE TABLE IF NOT EXISTS MEMBERSHIP_TYPE (
    DANG_THE NVARCHAR(10) NOT NULL PRIMARY KEY,
    GIA_GIAM INT
);

CREATE TABLE IF NOT EXISTS MEMBERSHIP (
    MA_THE NVARCHAR(20) NOT NULL PRIMARY KEY ,
    MA_KH NVARCHAR(20),
    DANG_THE NVARCHAR(10),
    NGAY_DK DATE NOT NULL ,
    NGAY_HH DATE NOT NULL,
    CONSTRAINT FK_MEM_MEMTYPE_DANG_THE
        FOREIGN KEY (DANG_THE) REFERENCES MEMBERSHIP_TYPE(DANG_THE),
    CONSTRAINT FK_MEM_CUS_MAKH
        FOREIGN KEY (MA_KH) REFERENCES CUSTOMER(MA_KH)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_PERMISSION(
    CHUC_VU NVARCHAR(20) NOT NULL PRIMARY KEY ,
    DESCRIPTION NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE(
    MA_NV NVARCHAR(20) NOT NULL PRIMARY KEY ,
    TEN NVARCHAR(40) NOT NULL,
    CA INT,
    CHUC_VU NVARCHAR(20) NOT NULL,
    SO_NGAY_LAM_VIEC INT,
    NOI_LAM_VIEC NVARCHAR(100),
    HE_SO DOUBLE,
    PASSWORD VARCHAR(100),
    NGAY_NHAN_CHUC DATE,
    NGAY_SINH DATE,
    DIA_CHI NVARCHAR(100) NOT NULL ,
    CCCD NVARCHAR(20) NOT NULL ,
    EMAIL NVARCHAR(40) ,
    PHONE NVARCHAR(20),
    GIOI_TINH NVARCHAR(10),
    CONSTRAINT FK_EMPL_EP_CHUCVU
        FOREIGN KEY (CHUC_VU) REFERENCES EMPLOYEE_PERMISSION(CHUC_VU)
);


CREATE TABLE IF NOT EXISTS BORROW_TICKET(
    MA_PHIEU NVARCHAR(20) NOT NULL PRIMARY KEY ,
    MA_NV NVARCHAR(20) NOT NULL,
    MA_CHITIET NVARCHAR(20) NOT NULL,
    MA_THE NVARCHAR(20) NOT NULL,
    CONSTRAINT FK_BT_MEM_MA_THE FOREIGN KEY (MA_THE) REFERENCES MEMBERSHIP(MA_THE)
);

CREATE TABLE IF NOT EXISTS BOOK_FAULT(
    MA_LOI NVARCHAR(20) NOT NULL PRIMARY KEY ,
    TEN_LOI NVARCHAR(40) NOT NULL ,
    HE_SO DOUBLE
);

CREATE TABLE IF NOT EXISTS BORROW_TICKET_DETAILS(
    MA_CHITIET NVARCHAR(20) NOT NULL PRIMARY KEY ,
    MA_PHIEU NVARCHAR(20) NOT NULL,
    MA_SERIES NVARCHAR(40) NOT NULL,
    NGAY_HENTRA DATE,
    NGAY_CHO_MUON DATE,
    TIEN_TAM_TINH LONG,
    TIEN_TONG LONG,
    MA_NVXN NVARCHAR(20),
    CONSTRAINT FK_BTD_BT_MA_PHIEU
        FOREIGN KEY (MA_PHIEU) REFERENCES BORROW_TICKET(MA_PHIEU),
    CONSTRAINT FK_BTD_BOOK_MASERIES
        FOREIGN KEY (MA_SERIES) REFERENCES BOOK(MA_SERIES)
);

CREATE TABLE IF NOT EXISTS BORROW_BOOK_TICKET_FAULT(
    MA_LOI NVARCHAR(20) NOT NULL,
    MA_CHITIET NVARCHAR(20) NOT NULL,
    SO_LUONG INT NOT NULL,
    CONSTRAINT FK_BTD_BBTF_MA_CHITIET
        FOREIGN KEY (MA_CHITIET) REFERENCES BORROW_TICKET_DETAILS(MA_CHITIET),
    CONSTRAINT FK_BF_BBTF_MA_CHITIET
        FOREIGN KEY (MA_LOI) REFERENCES BOOK_FAULT(MA_LOI)
);

CREATE TABLE IF NOT EXISTS SELL_TICKET(
    MA_PHIEU NVARCHAR(20) NOT NULL PRIMARY KEY ,
    MA_NV NVARCHAR(20) NOT NULL,
    MA_CHITIET NVARCHAR(20) NOT NULL,
    MA_KH NVARCHAR(20) NOT NULL,
    CONSTRAINT FK_ST_CUS_MA_KH FOREIGN KEY (MA_KH) REFERENCES CUSTOMER(MA_KH)
);

CREATE TABLE IF NOT EXISTS SELL_TICKET_DETAILS(
    MA_CHITIET NVARCHAR(20) NOT NULL PRIMARY KEY ,
    MA_PHIEU NVARCHAR(20) NOT NULL,
    HE_SO DOUBLE NOT NULL ,
    MA_SERIES NVARCHAR(40) NOT NULL,
    CONSTRAINT FK_STD_ST_MAPH FOREIGN KEY (MA_PHIEU) REFERENCES SELL_TICKET(MA_PHIEU),
    CONSTRAINT FK_STD_BOOK_MASERIES FOREIGN KEY (MA_SERIES) REFERENCES BOOK(MA_SERIES)
);



CREATE TABLE IF NOT EXISTS BOOK_BOOK_FAULT (
   MA_SERIES NVARCHAR(40) NOT NULL,
   MA_LOI NVARCHAR(20) NOT NULL ,
   CONSTRAINT PK_BOOK_BBF_MA_SERIES_LOI PRIMARY KEY (MA_SERIES, MA_LOI),
   CONSTRAINT FK_BOOK_BBF_MASERIES FOREIGN KEY (MA_SERIES) REFERENCES BOOK(MA_SERIES),
   CONSTRAINT FK_BF_BBF_MALOI FOREIGN KEY (MA_LOI) REFERENCES BOOK_FAULT(MA_LOI)
);